### ISSUE TITLE
Add ability to set userAgentRegex flags

### ISSUE THREAD

**Issue by drphrozen** [mperdeck/jsnlog#101]
It would be nice if we were able to add the ignore case flag for the user agent regex.

Either that or allow for the //i syntax in the userAgentRegex property.

**Comment by mperdeck** [comment]
Thanks for your suggestion. Because every change takes time and creates risk and complexity, I'm trying to figure out how useful allowing an ignore case flag would be before looking at implementation.

Just looked at some common user agents, which seem to be using case consistently. Also, I guess you can use | to match against lowercase and uppercase versions. So I'm not sure of the utility of this.

Could you show me some examples of where an ignore case flag would have saved you a lot of work?
