### ISSUE TITLE
New setting to throttle sending log messages

### ISSUE THREAD

**Issue by sergkr** [mperdeck/jsnlog#116]
(Continuing the discussion from #83)

It would be useful in some scenarios to have a `throttle` setting that ensures that we don't send too many server requests in too short a time period.

To give a real world example where this would be useful: we have a graphical flight planner application that supports various mouse-based chart interactions. We also have a global error handler that catches all errors and logs them to the server using jsnlog.js. Occasionally, we may have a bug in one of the chart interactions that results in an error being generated every time the user moves the mouse. This kind of scenario can result in a high number of server requests because of the frequency with which these kinds of errors get generated (basically every time a `mousemove` event fires in the chart, which is the primary component of the application where most of the user interaction takes place).

The existing batching functionality helps alleviate this somewhat (though we opted not to use it until #83 is fixed so we don't wind up losing messages), but ultimately we're interested in controlling the frequency of the requests on a time basis.

So, that would be my argument for having a `throttle` setting - there are legitimate scenarios where you can have a high frequency of log messages. Any interactive kind of application that runs potentially error-prone code in response to mouse events is one example.

There were a few concerns discussed in #83 that I'd like to address:

> If you throttle outgoing messages, the buffer holding the messages may fill up and you'll lose messages.

True, there's a greater likelihood messages with priority lower than `sendWithBufferLevel` will be lost if there's an additional delay due to throttling. However, if I understand correctly, these messages are only used to establish context, and they are already subject to being lost (if the user wants guaranteed delivery, they could increase the message priority, or adjust `sendWithBufferLevel`), so I don't see this as a big concern. Any messages with priority greater than or equal to `sendWithBufferLevel` should still have guaranteed delivery, even if we enable throttling.

> Browsers regularly fire off dozens of requests, when loading pages with lots of images, js files, etc.

Yes, but hopefully only during the course of page loading. Some of the interaction errors we saw in our application resulted in continuous log messages being sent over the course of an hour, as the user continues to interact with the application in a broken state.

> JSNLog has a number of features to cut down on the number of messages sent to the server, such as the option to prevent (near)duplicate messages.

I'm assuming you're referring to the `onceOnly` config option? That does look potentially handy, I wasn't aware of it before. But if I understand correctly, this requires that we know what to look for ahead of time, so it's only useful for *known* errors that we want to suppress. May be useful once we learn of a particular error that is prone to high log traffic - we can quickly push out an update that suppresses it so we're not overwhelmed with log messages (while we work on fixing the error). But I'm struggling to think of a way to use it generically, without knowing what to look for ahead of time.

> I'm concerned about the complexity added by the throttling feature - in the code base, and in the mind of the developer using JSNLog. For example, the timeout and the throttling features work against each other - if throttling would cause a message to be stuck in the buffer for 200ms while timeout is set to 50ms, what happens than? Note that every feature and complexity has to be described in the documentation on jsnlog.com.

Yeah, that could be a tricky one, especially from a documentation/understanding perspective. I would say `throttle` takes priority in this case - when the 50ms timeout runs out, before sending out the contents of the batch buffer, there may be an additional delay so as to respect the `throttle` setting (if there was a recent server request).

From a code perspective, here's how I'm thinking this would be implemented. The underscore.js library has a very concise implementation of the `throttle` method, which you can see here:

http://underscorejs.org/docs/underscore.html#section-82

As you can see, it's roughly 30 lines of JS (I'm not proposing we pull in the entirety of underscore.js - we should be able to just lift that single function from there, possibly replacing `_.now()` with just a `new Date()`). Using it is very simple - you just pass it the actual function that you want to execute, and it returns a new "wrapped" function with throttling behavior. So for instance, if you wanted to throttle `sendLogItems` to 100ms, you could just do something like this:

    var sendLogItemsThrottled = _.throttle(this.sendLogItems, 100);

Now, you can call `sendLogItemsThrottled` to your heart's content, but the underlying `this.sendLogItems` function will not execute more than once every 100ms. Pretty elegant, in my opinion. May require some more thought as to how to wire it up in the code exactly, as well as handle changing the throttle timeout if they call `setOptions`, but overall I don't think it's going to complicate the code *too* much.

> I'm trying to keep the download size of jsnlog.js in check.

Assuming the above approach sounds ok, the increase in size should be reasonable (30 additional lines of code for the throttle implementation, and hopefully not too many more to add the new config setting and properly integrate it).

**Comment by mperdeck** [comment]
Thanks for your detailed proposal!

** About losing messages due to limited buffer size - My mistake. This only relates to the buffer used with sendWithBufferLevel etc., not to the buffer used for batching. So this isn't a factor.

** About the number and frequency of messages, compared with say loading a page - I now understand that your app may rapidly throw exceptions during an entire session (which could take as long as an hour).

I guess there are 2 concerns here:
1) Frequency - number of log requests being sent to the browser per second
2) Total number of log requests sent to the server. If your app throws 100 exceptions per minute for an hour, that is a very large number of exceptions, especially with multiple browsers doing the same thing.

Specifically, I understand your concern is not so much the frequency of log entries being processed, but the frequency of log _requests_ being sent by the browser to the server.

You could use the maxMessages option on the jsnlog library itself to limit the number of log messages (as opposed to log requests) sent per page load. This will protect your server if multiple browsers send mouse movement messages at the same time. 

http://jsnlog.com/Documentation/Configuration/JSNLog

And/or you could use a large batch size, combined with the new timeout. For example, if sending 1 request per second is ok, and a mouse handler won't generate over 1000 exceptions per second, than you could set the batch size to 1000 and the timeout to 1 second. 

This limits your log requests to no more than 1 per second. And a single exception somewhere else in your app (not in the mouse handler) will be sent to the server with a delay of no more than 1 second.

** Cutting down number of messages with the onceOnly option - I appreciate that this relies on knowing some bit of text that will be common to the (near) duplicates, and on coding this into the app before it throws all these exceptions. 

I don't know how big your code base is or how badly structured it is. I guess it has a number of handlers that process mouse move events, and that these are complex enough to contain bugs that throw exceptions. 

Is it possible to find all places where mouse event handlers are set? You could then write a "universal mouse event handler" function that takes the actual handler as a parameter. This new function would call the handler inside a try-catch. The catch bit creates a new exception with a well known string (for onceonly) plus maybe other useful info (such as mouse x and y), and contains the original exception as an inner exception. Each mouse move event would than essentially be handled by this new method.

JSNLog includes support for inner exceptions, see:

http://jsnlog.com/Documentation/JSNLogJs/Exception

** Complexity added by the throttling feature - This is a huge issue for me, and the reason why I remain hesitant to include this feature. Not only does it need to be explained to the user (documentation), it also requires unit tests to ensure that later on I don't introduce bugs in this functionality.

**Comment by sergkr** [comment]
I understand your concern about the complexity of the throttling feature. I think a combination of your other suggestions would be an acceptable workaround in our scenario, particularly the large batch size with a one second timeout (once the timeout feature is implemented).

Thanks for your consideration!
