### ISSUE TITLE
Typescript import not working

### ISSUE THREAD

**Issue by JanEggers** [mperdeck/jsnlog#124]
Hi 

im using typescript 2.0.3 and just included jsnlog via npm and i use system.js to load stuff.

i get a typescript compiler error on importing jsnlog:

error TS2305: Build:Module '"[projectdir]/node_modules/jsnlog/Definitions/jl"' has no exported member 'JL'.

obviously this should work, can you give me a hint whats wrong with my setup?

I created a simple repro:

https://github.com/JanEggers/Playground/

JL is imported in:

https://github.com/JanEggers/Playground/blob/master/Playground.core/wwwroot/app/app.component.ts

**Comment by tombpevans** [comment]
I'm having the same issue, but I'm using the angular-cli, so webpack is used to load modules.

I've found this [article](http://karatejb.blogspot.co.uk/2016/10/angular2-build-spa-with-mvc-and-ng2-in_26.html) where jsnlog is being used with angular2, but jsnlog is not being loaded via a module loader, so it's not particularly helpful for me and doesn't seem like good practice.

**Comment by JanEggers** [comment]
i switched to:

var JL = require('jsnlog').JL;

and wrapped it with a service so i have type safety

**Comment by mperdeck** [comment]
Sorry for the very late response. Other priorities intervened. Thanks for your bug report.

About the error message
error TS2305: Build:Module '"[projectdir]/node_modules/jsnlog/Definitions/jl"' has no exported member 'JL'.

This is caused by the last line in 
[projectdir]/node_modules/jsnlog/Definitions/jl.d.ts
which is:
export default JL;

It will work if you replace this with
export { JL };

I'll fix this in the next release of JSNLog.
