### ISSUE TITLE
Serilog serverSideMessageFormat and structured logging

### ISSUE THREAD

**Issue by ghost** [mperdeck/jsnlog#140]
Following the instructions on http://jsnlog.com/Documentation/Configuration/JSNLog # serverSideMessageFormat and structured logging; when setting the serverSideMessgeFormat to "{ 'Sent': '%date', 'Browser': '%userAgent', 'Message': %jsonmessage }", produces this messge in serilog: message:[[[]], [[]]]
Furthemore, when no serverSideMessageFormat is set, it produces same output

netcoreapp1.1
JSNLog.AspNetCore Version="2.24.0"
Serilog.Extensions.Logging Version="1.4.0" />
Serilog.Settings.Configuration Version="2.4.0" />
Serilog.Sinks.Elasticsearch Version="5.3.0" />
Serilog.Sinks.File Version="3.2.0" />

**Comment by mperdeck** [comment]
So it always logs the same line?
message:[[[]], [[]]]

I can't reproduce this. If it is still happening for you, please publish a small application that reproduces this problem.

**Comment by khumphrey-sb** [comment]
I'm seeing what I think is the same issue.   The very strange thing is that it goes away when you attach the VS debugger.  So publishing locally to IIS or Azure, or even Ctrl+F5, is the where we're seeing it.  Doesn't seem related to any Environment settings.  I'll see if I can replicate in a small project.

While debugger is attached we get:

`"\"message\": \"There was an error performing the request\", \"data\": {
  \"xhr\": {
    \"readyState\": 4,
    \"responseText\": \"\",
    \"status\": 500,
    \"statusText\": \"Internal Server Error\"
  },
  \"url\": \"/login\",
  \"data\": {
    \"emailAddress\": \"sdf\"
  }
}, \"stack\": \"Function.20.Logger.log()@..\\..\\./Client/app/Global/Logger.ts:34:19\nFunction.20.Logger.logFatal()@..\\..\\./Client/app/Global/Logger.ts:30:15\n{anonymous}()@..\\..\\./Client/app/Global/HttpUtils.ts:16:23\nfire()@http://localhost:51951/dist/vendor.js:8546:31\nObject.fireWith [as rejectWith]()@http://localhost:51951/dist/vendor.js:8676:7\nprocess()@http://localhost:51951/dist/vendor.js:8900:22\""`

Otherwise we get:
`[[[]], [[]], [[]], [[[[]], [[]], [[]], [[]], [[]]]]]`

**Comment by khumphrey-sb** [comment]
OK, I can definitely replicate the issue.  Empty project with nothing but basic setup for Serilog and JSNLog:

While debugging I get: 
`[10:34:35 FTL] "testMessage": "this is an error"`

When Crtl+F5 I get:
`[10:35:02 FTL] [[[]]]`

I'm not sure if the problem is with Serilog or JSNLog, but any help would be appreciated.

I've attached a small sample project.
[CoreLogger.zip](https://github.com/mperdeck/jsnlog/files/1231605/CoreLogger.zip)

**Comment by tabberbock** [comment]
@khumphrey-sb @ghost . I had a similar issue and used the following workaround: 

https://stackoverflow.com/questions/45738682/serilog-jsnlog-net-core-logging-empty-json/48432927#48432927

For me it seemed to be caused trying to serialize the JSON.NET object that is created from deserializing the log message and changing the template message to` logger.LogTrace("{@logMessage}", message); `

**Comment by mperdeck** [comment]
Thanks for creating the repro project. Apologies for the late reply. I finally found time to look at this issue.

It seems to be Serilog related, and is not reproducible in .Net Core 2 (your project was in .Net Core 1). Details below.

**Solution**

Rather than spend time trying to fix the problem for Core 1, I've decided to make the next version of JSNLog.AspNetCore dependent on Core 2. This will have to happen anyway some time, so may as well do it now. 

I appreciate this doesn't help you as long as you use Core 1. My only suggestion is to upgrade to Core 2. 

**Analysis**

I reproduced the problem in the project you sent me. I then copied your solution to a new solution CoreLogger3UpgradeSerilog and added the core console logger:
            loggerFactory.AddSerilog();
            loggerFactory.AddConsole(); //<<<<<<<

Control-F5 showed that the message was showing correctly in the console when logged by the .Net Core console logger, but wrongly (as per your message) by the Serilog Console sink. Upgrading Serilog and JSNLog to the latest versions didn't help.

I then created a new .Net Core 2 website in Visual Studio 2017 (Community Edition), naming it Core2Site. Then created a version Core2SiteWithJsnLog of this with your changes. Still using the Serilog Console sink and the .Net Core console logger. Added Serilog file logging, because in Core 2, Visual Studio 2017 doesn't open the console when you hit control-F5.

After control-F5, I found the correct log entry in the log file created by Serilog.

I attached a zip file with the solutions I mentioned above.

[CoreLoggerAnalysis.zip](https://github.com/mperdeck/jsnlog/files/1669690/CoreLoggerAnalysis.zip)
