### ISSUE TITLE
LoggingAdapter Missing in  

### ISSUE THREAD

**Issue by Codewizard** [mperdeck/jsnlog#144]
When you download the sample project and the sample code the project works just fine due to the nuget package referencing netstandard1.6 but when you download package using net452 the project is missing the LoggingAdapter (and possibly other classes).  from the project.

**Comment by mperdeck** [comment]
I'm a bit confused. What are you trying to do? Which packages are you installing?

**Comment by danjohnso** [comment]
@mperdeck You remove the LoggingAdapter from the installs targeting full .NET Framework via the conditional compiler directive, which I think is a mistake.  Since MVC Core can target full framework you deprive full framework users from being able to use this.  In my case, I have to target full framework because of a downstream dependency, but I am still using MVC Core.  

You could add an additional target and raise the requirements to .NET Framework 4.6.1 to match .net core 2 which would still let you exclude the extension for non-core users.

**Comment by danjohnso** [comment]
Wow so I thought it was just the adapter that was missing, but going down the rabbit hole, everything about the .net core install is missing for full framework users.  

JSNLog is unusable in a .NET core full framework project.

**Comment by mperdeck** [comment]
Thanks for your bug report. This has now been fixed in release 2.24.1 (just gone live).
