### ISSUE TITLE
Upgrade to net.core 2.0 causes trace and debug to be received by the server but not logged

### ISSUE THREAD

**Issue by stefandascalu64** [mperdeck/jsnlog#148]
[jsnlog.AngularCoreDemo-master.zip](https://github.com/mperdeck/jsnlog/files/1304585/jsnlog.AngularCoreDemo-master.zip)

I was working on an app and figured after a while that my js logs were not being created. After a few trial and error attempts I linked the problem to the update to .Net Core 2.0.
As far as I can tell the messages are received by the server. but either JSNLog is not configured to pass them on or something has changed within core 2.0 that caused the messages to not be passed on.

My app uses Angular, Typescript, NLog and JSNLog.
I managed to find a small project and reproduce the issue when the project was updated to 2.0. It does't use NLog so the tracing is done on the debug console.
If you go to the page and click Create Log Item it should create 6 log entries for each of the severity levels but it only creates 4.

I can't find the problem described in any change log. Is there a configuration I am missing?

**Comment by mperdeck** [comment]
I'm sorry, I wasn't able to find the problem in your app. 

When compiling it with VS 2017 Community Edition, I got tons of errors (most common ones below). It could well be that these errors are due to my own environment rather than your code. I did install Net.Core 2.0 and upgraded Nuget, to no avail. Google was not very helpful.

If you find that the cause of the problem is a bug in JSNLog, please let me know (or better, send me a pull request). 


Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'TargetFrameworkAttribute' exists in both 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	Website	C:\Users\mperdeck\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.cs	4	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1703	Multiple assemblies with equivalent identity have been imported: 'C:\Users\mperdeck\.nuget\packages\microsoft.netcore.app\2.0.0\ref\netcoreapp2.0\System.Reflection.Emit.Lightweight.dll' and 'C:\Users\mperdeck\.nuget\packages\system.reflection.emit.lightweight\4.0.1\ref\netstandard1.0\System.Reflection.Emit.Lightweight.dll'. Remove one of the duplicate references.	Website	C:\Users\mperdeck\Downloads\jsnlog.AngularCoreDemo-master\jsnlog.AngularCoreDemo-master\Website\CSC	1	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'AssemblyTitleAttribute' exists in both 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	Website	C:\Users\mperdeck\Downloads\jsnlog.AngularCoreDemo-master\jsnlog.AngularCoreDemo-master\Website\obj\Debug\netcoreapp2.0\Website.AssemblyInfo.cs	20	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error		Package Microsoft.AspNetCore.Mvc 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.Mvc 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)

**Comment by stefandascalu64** [comment]
I don't know why the app doesn't build on your side, i have .net core and npm installed and all i need to do is press F5.
I have found a solution for my issue, After attempting to debug jsnlog and failing to some degree I finally found it sending messages to the logger.
The problem is in .Net core 2.0. The default level was increased. And the complexity of configuring the updated apps was also increased.

Sry for any inconvenience. I did not find out about this change until after further documentation.
https://stackoverflow.com/questions/45781873/is-net-core-2-0-logging-broken#_=_
