### ISSUE TITLE
No hook to check for user signed in

### ISSUE THREAD

**Issue by bcshores** [mperdeck/jsnlog#159]
I can't think of an actual security issue, but most of our site is blocked by .net until you are authenticated.  I can't see a way to do that sort of check here.  This means anyone external has access to this.  The main problem I see is if they decided to flood us they could do a DoS type of attack by just flooding our logs with messages.

Is there any way to catch the call to the server and make a choice based on whether to allow the logging or not?

**Comment by mperdeck** [comment]
There are a number of options.

If you use Owin or .Net Core, you could place your authentication check in the pipeline before the JSNLog middleware. That way, you can short circuit any request from a user who is not authenticated.
http://jsnlog.com/Documentation/DownloadInstall/ForAspNetCore
http://jsnlog.com/Documentation/DownloadInstall (see section "OWIN only")

Otherwise, you could create an OnLogging event handler that cancels the log request if the user is not authenticated:
http://jsnlog.com/Documentation/JavascriptLogging/OnLogging
