### ISSUE TITLE
jsnlog in MVC 5 project and NLog in class library project

### ISSUE THREAD

**Issue by nichovski** [mperdeck/jsnlog#173]
Hello guys,

@mperdeck thanks for this amazing project.

Here is my problem. I have multilayer C# solution where my logger is placed in a separate class library project that is referenced in all other projects. I wanted to configure jsnlog to send all logs to my other project and use that targets for storing my logs. 

At the moment I have only server-side logging, it looks like this:

`
   public ResultViewModel<dynamic> GetEvent(string someValue)
        {
            try
            {
                return this.myRepository.Get(someValue);
            }
            catch (Exception ex)
            {
                _loggingService.Error(ex);
                return ResultHelper<dynamic>.ReturnError(null, ex);
            }
        }
`

_loggingService.Error(ex); is in my class library project and it looks like this:

`     public void Error(string message, Exception x)
        {
            _logger.Error(x, message);
        }
`

Here you can find the whole LoggingService: https://pastebin.com/QC6L6pT1

Any suggestions on how I can do that?

Thank you
Bogdan

**Comment by mperdeck** [comment]
I understand you essentially created your own server side logger, and you want JSNLog to talk to your logger.

If you use .Net Core - JSNLog simply uses the standard logging infrastructure. 
https://asp.net-hacker.rocks/2017/05/05/add-custom-logging-in-aspnetcore.html
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1

Otherwise, you can write a handler for the OnLogging event, which then calls your logger:
http://jsnlog.com/Documentation/JavascriptLogging/OnLogging
