### ISSUE TITLE
Can't override defaultAjaxUrl

### ISSUE THREAD

**Issue by xeniak** [mperdeck/jsnlog#194]
I am running JSNLog in an Angular app. Because of the requirements of the backend, I've overridden the defaultAjaxUrl:
`JL.setOptions({defaultAjaxUrl: new/url})`

JSNLog does log to new/url, but it also keeps trying to POST to /jsnlog.logger, which doesn't exist.

**Comment by mncoldsmoke** [comment]
My issue is related. I need to tell JSNLog where my logger (URL) is, but there doesn't seem to be a way to do that because JL.setOptions does NOT work at all. 

There is zero documentation for seeing this value locally, and the actual NPM package seems to have a method signature that is unreachable to set the defaultAjaxUrl property.

**Comment by mperdeck** [comment]
Can't reproduce these issues. Also please refer to https://jsnlog.com/Documentation/HowTo/CORS
