### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by NCC1701M** [mperdeck/jsnlog#202]
The code hasn't changed in a year. No replies to new issues since January.

I would like to know if this project is still active

**Comment by mperdeck** [comment]
It is still active, but on a low level. This because 1) I'm flat out with other things; 2) it continues to work well; 3) I get very few issues, probably because the most common use case is pretty simple.

It continues to be highly useful though. I use it at work, where it surfaces client side exceptions on our live servers.

**Comment by NCC1701M** [comment]
Great, because I needed some information from the website and it was down for quite some time. So I want be sure about the project status.
