### ISSUE TITLE
404 Not Found Error when using IIS (7.5) but ok with VS Development Server (if not IE)

### ISSUE THREAD

**Issue by ghost** [mperdeck/jsnlog#34]
Hi,
When I run my MVC 5.1.2 (Razor 3.1.2) application via Visual Studio 2012, JSNLog doesn't work and fails with errors: "Failed to load resource: the server responded with a status of 404 (Not Found)" and "POST http://localhost/jsnlog.logger 404 (Not Found) " if I use IIS(7.5).  If I change my project to use the Visual Studio Development Server, it works.  I have another MVC project where JSNLog works using IIS and both applications are using the same Applicaiton Pool in IIS.  

Please note that when using IE 9 as a browser, it doesn't work in IIS or the Visual Studio Development Server.

I am running Windows 7 64-bit and both applications are set up as Virtual Directories off the Default Website in IIS.

Please help,

**Comment by amit4540** [comment]
hi ,

I am also facing the same issue, log entries are written when i try to run the site from local iis , but once i deploy i get a blank log file. My url looks like localhost/sitename (its a intranet site). Once i remove the '/' from  /jsnlog.logger from jsnlog.js and min file it works file and logs are written properly.

I saw your above comments , i am using version 2.17.0 and facing this issue.. Please suggest me if this is the right way?

**Comment by mperdeck** [comment]
"localhost" indicates the site is on your local machine. I guess that is also your server. I'm not sure whether your site is configured as an Application in IIS. However, JSNLog supported this since 2.7.0. So right now I don't have enough information to figure out why it doesn't work.

JSNLog allows you to configure the url of the endpoint on the server where it sends the log requests. Maybe that solves the problem for you. It is described at:
http://jsnlog.com/Documentation/HowTo/CORS
