### ISSUE TITLE
Method not found: 'Common.Logging.ILog Common.Logging.LogManager.GetLogger(System.String)'

### ISSUE THREAD

**Issue by joeygrandville** [mperdeck/jsnlog#55]
I'm trying to log javascript and ajax errors on an MVC 5 project that has elmah set up. The log is working, but instead of storing information related to the exception, it's popping the following message:

<code>System.MissingMethodException</code>
<code>Method not found: 'Common.Logging.ILog Common.Logging.LogManager.GetLogger(System.String)'.</code>

![capture](https://cloud.githubusercontent.com/assets/10599156/5801866/454bfd86-9fce-11e4-91d8-22e160db0b76.PNG)

Is it possible that the called methods are deprecated?
I've searched but couldn't find any references to the issue I'm having

For ajax errors, I'm using the folllowing code:

<code>$(document).ajaxError(function (event, jgXHR, ajaxSettings, thrownError) {</code>
<code>    JL("siLogger").fatalException({</code>
<code>        "msg": "AJAX Exception",</code>
<code>        event: event,</code>
<code>        jgXHR: jgXHR,</code>
<code>        ajaxSettings: ajaxSettings,</code>
<code>        thrownError: thrownError</code>
<code>    }, {});</code>
<code>});</code>

**Comment by Marcin-Szydlowski** [comment]
I have the same for configuration MVC 5 + JSNLog + NLog. If I log something to console, this works great, but If I try log to files, no matter by using NLog.config file or do it via 'INLINE' in web.config with appropriate section with targets and rules, then this error occures. In my case the problem is caused by new versions of these libraries: Common.Logging (3.0.0), Common.Logging.Core (3.0.0) and NLog (3.2.0.0). I saved theirs sources by ILSpy, but I cannot build them even If I link lacking references.

I downloaded sample solution (JSNLogSimpleWorkingDemos) from this site and using 'EmptyNLog' project - everything works and looks fine. But right after changed versions of mentioned libraries it stopped working for files and gave me the same message.

But as I said, the problem is for newest versions of these files. If it doesn't matter, try install previous versions.

**Comment by IanYates** [comment]
I spent a good chunk of yesterday morning getting JSNlog, SeriLog, Common Logging, etc all playing nicely.  Frustrating, but that was due to the Common.Logging library's changed surface area (and hence major version bump).

The fix for me was to revert to the 2.x series of Common.Logging and, for ease of use and customisation, bring in @mperdeck 's code for Common.Logging->SeriLog into my project and reference it  (I was still getting DLL reference issues otherwise).

It'd be nice if JSNlog had some events/observables we could wire up and use that to point to our own logging rather than relying on the "magic" that is Common.Logging.

Anyway - I'm now sprinkling JSNlog logging throughout my TypeScript code and am looking forward to getting a better end-user debug experience.  Thanks for the library :)

**Comment by mperdeck** [comment]
Thanks all for the bug report.

It turns out you're not alone. Anybody using a third party package (just not JSNLog) that in turn uses Common.Logging is having problems, because Common.Logging 3 is not binary compatible with Common.Logging 2. It seems this is caused by a misunderstanding on the part of the Common.Logging team on how NuGet (doesn't) work:
https://github.com/net-commons/common-logging/issues/74

I'll try to come up with a solution in the coming days. Will keep you posted.

**Comment by joeygrandville** [comment]
Thanks a lot for the replies. Will try to downgrade common.logging, but anyway will be looking forward a definitive solution

**Comment by mperdeck** [comment]
I just released version 2.7.11 of JSNLog, which binds against Common.Logging 3. I also updated jsnlog.log4net, etc., so they use version 3 compatible adapters.

Could you please give this a try at your end and let me know whether it worked for you. That would be much appreciated.

**Comment by joeygrandville** [comment]
Thank you very much!!

**Comment by Marcin-Szydlowski** [comment]
Works great! Thank you.
