### ISSUE TITLE
Unknown logger logs in the the scope of the rootLogger

### ISSUE THREAD

**Issue by fgieseke** [mperdeck/jsnlog#60]
I have 2 loggers defined
    <logger appenders="consoleAppender;ajaxAppender" />
    <logger name="Workflow" appenders="consoleAppender" level="TRACE"/> 

Now I would log let's say: (misspelling Workflow -> Wokflow)
JL("Wokflow").debug("Start");
JL("Wokflow").debug("Value 1");
...
JL("Wokflow").debug("Value n");
JL("Wokflow").debug("End");

What happens?
JL("Wokflow") creates a new logger on the fly with the rootLogger as it's descendant.
So every logmessage is sent to the rootLogger and to the ajaxAppender and all those Messages get fired into the serverside log.

You should separate creation from retrieval and not hide errors.

@Html.Raw(JSNLog.JavascriptLogging.Configure())
should output
var logger = JL.createLogger("Workflow").

// js-code should use
myLogger = JL.getLogger("Worflow"). // <- misspelled
myLogger.debug("start"); // -> NULL-Reference Exception! Error found and not hidden away.

Here's my hack for this situation. 
(Looking in the rootLogger in advance and checking if there is a property __.__<loggername>. If not the logger is not wellKnown. I delete the appenders and add a default ConsoleAppender instead.)

var loggerName = "Worflow";
var wellKnown = false;
var proto = this._jsnLogger["__"];
if (proto)
  wellKnown = typeof proto["__" + loggerName] === "object";
var jsnLogger = JL(loggerName);
if (!wellKnown) {
      console.warn("No logger '{0}' defined! Using new Logger with ConsoleAppender!", loggerName);
      jsnLogger.appenders = new Array<JSNLogAppender>();
      jsnLogger.appenders.push(JL.createConsoleAppender("appenderFor" + loggerName));
}

**Comment by mperdeck** [comment]
Thanks for your feedback.

I understand that you're recommending that JSNLog only allow you to use loggers that have been explicitly created. 

However, as you will have seen, this is contrary to the philosophy behind JSNLog, and Log4Net/Log4J that inspired it. The idea is that you can dynamically create a logger in your JavaScript code, and optionally add options to some loggers and their descendents.

I appreciate your preference for essentially strongly typing the loggers. This is why I wrote jsnlog.js in TypeScript rather than JavaScript.

On the other hand, creating loggers on the fly has the advantage that:
* It is much easier to introduce lots of loggers, such as loggers with the same name as the namespace/function they appear in;
* But more importantly, it ties in with how Log4Net and other Log4J based loggers work - making it easier for new users to understand.

In the end, to me the advantages of creating loggers on the fly (that is, combining creating and retrieval as you put it) outweigh the disadvantages.

**Comment by fgieseke** [comment]
It's ok to create loggers on the fly. The "error" is, that it automatically inherits the rootlogger settings. As you can see in my code I  log a warning to the rootlogger, telling that an undefined logger was created on the fly, and then I replace the appendercollection of the new logger to only use the console logger.
The problem is, that in production code you can't turn "OFF" a logger that isn't defined.
