### ISSUE TITLE
getting $digest already in progress error

### ISSUE THREAD

**Issue by bigerock** [mperdeck/jsnlog#62]
right after my error gets thrown, i get the following error messages (twice): 
    
    Uncaught Error: [$rootScope:inprog] $digest already in progress

i'm throwing an error on the return of an $http.get in angularjs like this:

return $http.get('someurl').then(function(data){
    throw new Error('oops');
});

it's after this error gets logged to the console that i get the above error message. any ideas?

**Comment by mperdeck** [comment]
This is an AngularJs problem (it often happens when you call apply, but  Angular is already processing events). JSNLog doesn't use AngularJs internally, so I don't think it is causing these errors.

You may find this interesting:
http://stackoverflow.com/questions/12729122/prevent-error-digest-already-in-progress-when-calling-scope-apply
http://stackoverflow.com/questions/14838184/error-digest-already-in-progress

**Comment by bigerock** [comment]
thanks. it seems to happen after i installed the jsnlog code in angularjs and do something to throw an error - such as write a fake function name like 'dosomething()' or even throw a new error. i guess i'll keep digging and see if i can determine the cause. i don't have any apply methods that i expressly call.

**Comment by Devofure** [comment]
Hi, i encounter the same error as you describe with the same message, my problem was this implementation from the example.

    .factory('$exceptionHandler', function () {
        return function (exception, cause) {
            JL('Angular').fatalException(cause, exception);
            throw exception;
       };
    })
my solution was this:

    .factory('$exceptionHandler', function () {
        return function (exception, cause) {
            JL('Angular').fatalException(cause, exception);
            setTimeout(function() {
                throw exception;
            }, 0);
       };
    })

I hope it helps others with the same problem
