### ISSUE TITLE
`maxMessages` attribute should work only for AjaxAppender

### ISSUE THREAD

**Issue by VyacheslavPritykin** [mperdeck/jsnlog#69]
`maxMessages` attribute restricts to total number of log messages that are sent to the server and client sides, rather than only the server sides.

This code

````
if (!(JL.maxMessages == null)) {
    if (JL.maxMessages < 1) {
        return;
    }
}
// If maxMessages is not null or undefined, then decrease it by the batch size.
// This can result in a negative maxMessages.
// Note that undefined==null (!)
if (!(JL.maxMessages == null)) {
    JL.maxMessages -= this.batchBuffer.length;
}
````

should be executed only for `AjaxAppender`.

**Comment by mperdeck** [comment]
Apologies for the late reply. Thanks for pointing this out. You're probably right, it may well have been better to have a maxMessages per appender rather than library wide. I guess this doesn't matter all that much though - because people using maxMessages will probably send all log messages to the server.
