### ISSUE TITLE
HttpContext.Current.Session is Null

### ISSUE THREAD

**Issue by maldim** [mperdeck/jsnlog#79]
I am using Jsnlog Elmah with AngularJS and MVC. Whenever there is a POST call to the server with jsnlog.logger, the HttpContext.Current.Session always Null. What I found was, LoggerHandler.cs class inherits only IHttpHandler and not IRequiresSessionState interface. And when it inherits from both, I was able to get the Session State. May be it's a bug or an enhancement required?

Thanks,
Dimpy

**Comment by mperdeck** [comment]
Thanks for your suggestion. I've now added IReadOnlySessionState to the LoggerHandler class. This is in the last release 2.10.0.

I used IReadOnlySessionState instead of IRequiresSessionState because IReadOnlySessionState doesn't take an exclusive lock on the session data, so would be better for performance. I guess that Elmah only needs read only access to the session data.
