### ISSUE TITLE
batchSize timeout so that messages are not lost

### ISSUE THREAD

**Issue by drmorale** [mperdeck/jsnlog#83]
In the case that the exact batchSize is not hit, it would be useful to have either a set timeout or allowing a timeout to be configured such that messages being batched together are sent after the timeout and therefore not lost simply because a batch amount was not met. Batching should be a debounce throttle, not a true batch. If the batchSize is 3, and 4 messages are received, the 4th possibly being different than the rest and thus important for logging, there should be a way to get both the performance improvements from batching while also not losing any possibly important information.

**Comment by mperdeck** [comment]
This seems like a real improvement to me, thanks for the suggestion. I've marked it as an enhancement, but I don't know when I'll have time to do this.

**Comment by drmorale** [comment]
I'll take care of it! Let me know if there's a direction you can point me in!

**Comment by mperdeck** [comment]
Thanks for taking this on.

I can see these things that need to be done:

* Introduce a new config parameter that allows you to set the timeout in milli seconds. This needs to be done in both the server side package JSNLog (so you can set this in the web.config) and in the client side library jsnlog.js

* Come up with a good default for that config parameter, and decide how to switch off the timeout feature (maybe if the timeout parameter is -1?)

* Introduce the timer etc. in jsnlog.js  

* Update the TypeScript definition in
https://github.com/mperdeck/jsnlog.js/blob/master/jsnlog_interfaces.d.ts

* There is testing code in JSNLog (https://github.com/mperdeck/jsnlog, for both the C# and the JavaScript). Add tests there for your new functionality.

This will require changes in
https://github.com/mperdeck/jsnlog.js
https://github.com/mperdeck/jsnlog

jsnlog.js is actually written in TypeScript, in file jsnlog.ts.  The minify.bat batch file compiles the .ts file to the .js file. So you'll need to modify the .ts file.

I would suggest searching both projects for the identifier
batchSize

This will show you 1) how to add a new parameter; and 2) where the batching code is located.

**Comment by JanisE** [comment]
+1. Also, an option to send all the batched messages upon a page unload - even if the timeout is not reached - would be great.

**Comment by mperdeck** [comment]
@tparnell8 @JanisE @drmorale 
I totally concur with having a timeout on the buffer.

I'm super busy at the moment. However, if someone were to send me a PR to implement this buffer timeout, that would certainly help move things along.

**Comment by tparnell8** [comment]
I will do it...probably drop the PR week of the 15th. I am pretty busy until then.

**Comment by sergkr** [comment]
Any updates on this? This would be very useful in a project I'm working on. I would be willing to contribute a PR.

**Comment by mperdeck** [comment]
The status is that it hasn't been done. I would welcome a PR. Note that the timeout would have to be configurable (in ms), both in JavaScript and via the server side web.config / JsnlogConfiguration.

**Comment by sergkr** [comment]
Sounds good, I'll start taking a look this weekend.

**Comment by TerribleDev** [comment]
Yeah sorry...uhh life happened and then I didn't get to it... Thanks @sergkr

**Comment by sergkr** [comment]
No worries @TerribleDev, been there before :-)

I started looking into this earlier and ran into a question. Do we want the `timeout` parameter to also perform throttling, or is it only used for ensuring no messages get lost because the batch buffer never got filled? I see these as potentially two separate use cases, so I'm not sure we want one parameter to control both.

Also, if we also want it to do throttling, do we want that to be a leading-edge throttle (i.e., send out the first batch immediately, then start the timer), or a trailing-edge throttle (i.e., wait for the timeout to elapse before sending anything)? Might be a minor point, but thought I'd ask...

As an example, let's say `batchSize` is set to 5 messages, and `timeout` is set to 100 ms. Now consider a scenario where 50 messages get logged within a very short time period (under 100 ms). What do we want to have happen:

* **No throttling:** 10 server requests (each containing 5 messages, as determined by `batchSize`), each issued immediately as soon as the batch buffer gets filled.
* **Leading-edge throttle:** 2 server requests, the first containing 5 messages (gets sent out as soon as the batch buffer got filled), and the second containing the remaining 45 messages (gets sent out once the 100ms timeout has elapsed).
* **Trailing-edge throttle:** 1 server request containing all 50 messages, sent 100 ms after the first message got logged.

Personally, I want the throttling functionality, I'm just not sure it should be controlled by the same parameter. In the above scenario, `batchSize` is set to 5, but the actual number of messages may be different. Maybe not a big deal? Or should we split this out as a `batchTimeout` parameter that handles the use case of ensuring no messages get lost, and a separate `throttle` parameter that handles the other use case of ensuring we don't send too many requests in too short a time period?

**Comment by mperdeck** [comment]
I guess you're talking about 2 different features - 
"timeout" ensures that no message is stuck in the buffer for longer than a given period
"throttling" ensure a minimum time interval between 2 requests to the server

I can 100% see the business case for the "timeout" feature.

But I'm not sure at all about the "throttling" feature:

1) in my view, in 99% of cases where jsnlog.js sends a log request, the event causing it is relatively rare. That is, it is very unlikely that a given browser tries to send 100s or 1000s of messages in one go, for these reasons:

I think that by far the most common case for sending a log request in general is that the JavaScript code throws an uncaught exception that then gets handled by the window.onerror handler. For example, the end user presses a button, this runs some buggy JavaScript throwing an exception, leading to a request to the server. Frequency of log requests is very low here.

Another scenario is an AJAX request timing out - the JS sends a log request to the server and asks the user to try again.

2) If you throttle outgoing messages, the buffer holding the messages may fill up and you'll lose messages.

3) Browsers regularly fire off dozens of requests, when loading pages with lots of images, js files, etc.

4) JSNLog has a number of features to cut down on the number of messages sent to the server, such as the option to prevent (near)duplicate messages.

5) I'm concerned about the complexity added by the throttling feature - in the code base, and in the mind of the developer using JSNLog. For example, the timeout and the throttling features work against each other - if throttling would cause a message to be stuck in the buffer for 200ms while timeout is set to 50ms, what happens than? Note that every feature and complexity has to be described in the documentation on jsnlog.com.

6) I'm trying to keep the download size of jsnlog.js in check. 

Right now, I would be grateful for a pull request that simply implements the timeout (keeping it as simple as possible) - and that doesn't implement throttling. That would be a quick win.

Later on, _if_ you manage to convince me of the merits of throttling, you could always tackle that in a second pull request :-)

**Comment by sergkr** [comment]
I agree, let's keep these separate... though I do want to make a case for throttling as well. I'll open a separate issue where we can continue that discussion.

**Comment by mperdeck** [comment]
The latest release 2.24.0 introduces a new property on appenders "batchTimeout". Setting this (in ms) guarantees that a message won't sit in the batch buffer for longer than the given time out.

http://jsnlog.com/Documentation/Configuration/JSNLog/AjaxAppender
http://jsnlog.com/Documentation/JSNLogJs/AjaxAppender/SetOptions
