### ISSUE TITLE
Why is 2.15 nuget package depending on much more than 2.14

### ISSUE THREAD

**Issue by saberone** [mperdeck/jsnlog#92]
I tried installing nuget package in a 4.5.1 targetted project. But that fails to install. If I install 2.14 installation is fine. 

If I use a clean .net 4.5 MVC project then the latest version fails to install.

``` Unable to resolve dependency 'Microsoft.AspNet.Http.Abstractions'. Source(s) used: 'nuget.org', ```

I'm using Visual Studio 2015 update 1.

**Comment by mperdeck** [comment]
The 2.15 version targets two different .Net versions:
If you run .Net 4.5 or lower, it has pretty much the old set of dependencies
If you run .Net 4.5.1 or higher, it allows you to use JSNLog with ASP.NET 5, which requires a different set of dependencies.

I understand that the Nuget package doesn't install correctly in your case. I'll look into this over the weekend.

**Comment by mperdeck** [comment]
You wrote:
If I use a clean .net 4.5 MVC project then the latest version fails to install.

Would you be able to put this specific project on github?
That would make it easier for me to reproduce the situation at my end.

**Comment by kawazoe** [comment]
I am also seeing this issue. The problem lies in the new Microsoft packages which are still in prerelease. Unless you include prerelease packages, nuget won't find them when resolving JSNLog's dependencies.

Besides, these packages are only useful when dealing with Asp.Net 5. I've seen this issue in a Asp.Net 4 project. Perhaps there should be two different package to prevent fetching unneeded dependencies?

**Comment by mperdeck** [comment]
I've released a new version 2.15.1 that should solve this issue. You should be able to install this into an ASP.NET 4.x project without error messages.
