### ISSUE TITLE
jsnlog appenders in jsonly

### ISSUE THREAD

**Issue by Rlee13** [mperdeck/jsnlog#99]
Hi, I am trying to use jsnlog in js only mode:
`var appender = JL.createAjaxAppender("mylogger");
JL.setOptions({
    "defaultAjaxUrl": "api/jsnlog.logger",
    "appenders": [appender],
});
appender.setOptions({
    "storeInBufferLevel": JL.getTraceLevel(),
    "level": JL.getFatalLevel(),
    "sendWithBufferLevel": JL.getFatalLevel(),
    "bufferSize": 5
});
for (var i = 0; i < 10; i++) {
  JL("mylogger").info("from appender: msg #" + i);
}
JL("mylogger").fatalException("End of log messages.");`
Here I would expect to see the last 5 messages printed together with the end message - instead the messages are printed as they come on the server's console. 
(I skimmed through the code on the master branch and running the above code the JL().appenders array contains only the default appender no matter how many I define).
Any help with this problem is greatly appreciated.

**Comment by mperdeck** [comment]
I think you are trying to add the "mylogger" appender with the line
JL.setOptions({ "defaultAjaxUrl": "api/jsnlog.logger", "appenders": [appender], });

However, this attempts to set appenders for the library as a whole - and it doesn't have an appenders option. I guess that you actually want to set the appenders option of the nameless logger:

JL().setOptions({ "appenders": [appender], });

That's JL() instead of JL.

This is described further at
http://js.jsnlog.com/Documentation/JSNLogJs/JL/SetOptions
http://js.jsnlog.com/Documentation/JSNLogJs/Logger/SetOptions
